api = "0.7"

[buildpack]
  homepage = "https://github.com/naveeninitializ/node-engine"
  id = "naveeninitializ/node-engine"
  name = "Naveen Buildpack for Node Engine"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/naveeninitializ/node-engine/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/optimize-memory", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  

[[stacks]]
  id = "*"
